Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -66,4 +66,14 @@ jobs:
         run: |
           echo "Job started"
           sleep 10
-         
+          
+  notification-failed: 
+    runs-on: ubuntu-latest
+    needs: build-a
+      if ${{ needs.build.result == 'failure' || failure()}}
+    steps:
+      - name: notify
+        run: |
+          echo "Job Failure"
+          sleep 10
+              
